### ISSUE TITLE
Embed your MNS profile card on your website

### ISSUE THREAD

**Issue by shd101wyy** [Myobu-Guardians/realm#2]
![image](https://user-images.githubusercontent.com/1908863/199288155-715564f8-884d-4484-b634-7dd0d2ef9be9.png)

We now support embedding your MNS profile card on your website! Register for your MNS at https://protocol.myobu.io/#/mns, then copy the `iframe` code at the bottom to embed your profile card on your website!

**Comment by kirito-m** [comment]
Cool I will publish this :+1:
